In [1]:
import torch

In [2]:
z = torch.zeros(5, 3)
print(z)
print(z.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32


In [3]:
i = torch.ones((5, 3), dtype=torch.int16)
print(i)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


In [4]:
torch.manual_seed(1729)
r1 = torch.rand(2, 2)
print('A random tensor: ')
print(r1)

r2 = torch.rand(2, 2)
print('\nA different random tensor: ')
print(r2)

torch.manual_seed(1729)
r3 = torch.rand(2, 2)
print('\nShould match r1: ')
print(r3)

A random tensor: 
tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])

A different random tensor: 
tensor([[0.4216, 0.0691],
        [0.2332, 0.4047]])

Should match r1: 
tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])


In [5]:
ones = torch.ones(2, 3)
print(ones)

twos = ones * 2
print(twos)

threes = ones + twos
print(threes)
print(threes.shape)

r1 = torch.rand(2, 3)
r2 = torch.rand(2, 3)
r3 = r1 + r2
print(r3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[3., 3., 3.],
        [3., 3., 3.]])
torch.Size([2, 3])
tensor([[0.8344, 0.6629, 0.8460],
        [0.5566, 0.2616, 1.4962]])


In [6]:
r = torch.rand(2, 2) - 0.5 * 2
print('A random matrix, r: ')
print(r)

print('\nAbsolute value of r: ')
print(torch.abs(r))

print('\nInverse sin of r: ')
print(torch.asin(r))

print('\nDeterminant of r: ')
print(torch.det(r))
print('\nSingular Value Decomposition of r: ')
print(torch.svd(r))

print('\nAverage and Standard deviation of r: ')
print(torch.std_mean(r))
print('\nMaximum value of r: ')
print(torch.max(r))

A random matrix, r: 
tensor([[-0.0022, -0.6116],
        [-0.3071, -0.8297]])

Absolute value of r: 
tensor([[0.0022, 0.6116],
        [0.3071, 0.8297]])

Inverse sin of r: 
tensor([[-0.0022, -0.6581],
        [-0.3122, -0.9785]])

Determinant of r: 
tensor(-0.1860)

Singular Value Decomposition of r: 
torch.return_types.svd(
U=tensor([[-0.5599, -0.8286],
        [-0.8286,  0.5599]]),
S=tensor([1.0611, 0.1753]),
V=tensor([[ 0.2410, -0.9705],
        [ 0.9705,  0.2410]]))

Average and Standard deviation of r: 
(tensor(0.3608), tensor(-0.4376))

Maximum value of r: 
tensor(-0.0022)
